### ISSUE TITLE
Separate encrypted lookup path entirely

### ISSUE THREAD

**Issue by masih** [ipni/indexstar#127]
The double hash multicodec code is not dedicated to encrypted records. Therefore we cannot implicitly assume that it represents one. 

Separate encrypted lookup path by adding `/encrypted` prefix.

Context: 
 * https://github.com/ipfs/specs/pull/421#discussion_r1237036585

**Comment by gammazero** [comment]
If an indexer only accepts encrypted records, then this will not be needed since the indexer will assume everything is encrypted.

**Comment by gammazero** [comment]
Does this only apply to the `delegatedTranslator` at the `/routing/v1/` path, or does this apply to all queries (`/cid/`, `/multihash/`, etc.)?

**Comment by masih** [comment]
All queries.

For HTTP delegated routing, the semantics are not finalised [though close to be](https://github.com/ipfs/specs/pull/421).
For IPNI we should separate, encrypted queries from non encrypted and remove implicit assuptions that the multicodec would be of kind double hash.
