### ISSUE TITLE
Bitswap provider protocol id is incorrect

### ISSUE THREAD

**Issue by guseggert** [ipni/indexstar#50]
```
$ curl -s https://dev.cid.contact/routing/v1/providers/bafykbzacedzugqdzfjjbd4pgsvwrpkfdpk7rzfrsgwqj2kehxv2ffjy2tlny6 | jq -r '.Providers[].Protocol'
transport-bitswap
transport-graphsync-filecoinv1
```

The correct protocol id for bitswap is `bitswap`. (These are intentionally different from multicodec names so that they can be versioned without having to add a new multicodec code.)

**Comment by willscott** [comment]
noting that the thing the indexer gets from upstream is a multicodec code that it's translating here. do we really want custom logic to turn, specifically, `transport-bitswap` as named there into `bitswap`. because that seems like the path you're asking for?
