### ISSUE TITLE
Measure traffic volume on `PUT` requests to `/routing/v1/*

### ISSUE THREAD

**Issue by masih** [ipni/indexstar#54]
Add metrics that measure the number of requests requesting `PUT` on `/routing/v1/*` in order to build understanding of volume event though `PUT` on that path is not implemented by indexstar.

- [x] Add new metrics: #55 
- [ ] Deploy to `dev.cid.contact`
- [ ] Deploy to production `cid.contact`

**Comment by lidel** [comment]
cc https://github.com/ipfs/specs/pull/337 @guseggert @ajnavarro
