### ISSUE TITLE
Add metrics to get query response by metadata protocol ID

### ISSUE THREAD

**Issue by masih** [ipni/indexstar#88]
Add metrics to measure of the results returned what count had what protocol ID, for GraphSync, BitSwap and Other.

**Comment by ischasny** [comment]
Who is going to be the user of that feature?

**Comment by masih** [comment]
As in who is going to use the metrics collected? 

If so, see: https://filecoinproject.slack.com/archives/C046PNJ9QSU/p1677714854178589

**Comment by ischasny** [comment]
> As in who is going to use the metrics collected?
> 
> If so, see: https://filecoinproject.slack.com/archives/C046PNJ9QSU/p1677714854178589

Yes, thanks Masih
